[target.thumbv6m-none-eabi]
# Use probe-rs for running/flashing
runner = [
  "probe-rs", "run",
  "--chip", "STM32F072RB",
  "--log-format", "{t} {L} {s}",
]

[build]
# Set the default target
target = "thumbv6m-none-eabi"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Use flip-link to detect stack overflows during development
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

# tip: run `cargo clean` after changing these values
[env]
# default = "error"; other options: warn, info, debug, trace, off
# to set by module: "warn,{crate}::{mod}=trace"
DEFMT_LOG = "debug"
DEFMT_RTT_BUFFER_SIZE = "1024"
